apiVersion: v1
kind: Service
metadata:
  name: basic-data-service
spec:
  selector:
    app: basic-data-api-pod
  ports:
  - port: 5000
    targetPort: 80
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: ocelot-gateway-service
spec:
  selector:
    app: ocelot-gateway-pod
  ports:
  - port: 9000
    targetPort: 9000
  type: LoadBalancer
